# Generated by Django 3.2.19 on 2023-05-19 13:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Setup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_in', models.DateTimeField(default=datetime.datetime(2023, 5, 19, 13, 8, 56, 304770, tzinfo=utc))),
                ('datetime_out', models.DateTimeField(default=datetime.datetime(2023, 5, 19, 13, 8, 56, 304786, tzinfo=utc))),
                ('description', models.TextField(help_text="Provide specific details of the customer's setup request")),
                ('status', models.IntegerField(choices=[(0, 'Incomplete'), (1, 'Complete'), (2, 'Partially Complete'), (3, 'Awaiting Parts')], default=0)),
                ('payment_method', models.IntegerField(choices=[(0, 'Cash'), (1, 'Bank Transfer'), (2, 'PayPal'), (3, 'Other')], default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='setups.setup')),
                ('name', models.CharField(max_length=80)),
            ],
        ),
    ]
