# Generated by Django 3.2.19 on 2023-05-19 15:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0004_auto_20230519_1637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instrument',
            old_name='post_bridge_pu_height',
            new_name='post_bridge_pickup_height',
        ),
        migrations.RenameField(
            model_name='instrument',
            old_name='post_middle_pu_height',
            new_name='post_middle_pickup_height',
        ),
        migrations.RenameField(
            model_name='instrument',
            old_name='post_neck_pu_height',
            new_name='post_neck_pickup_height',
        ),
        migrations.RenameField(
            model_name='instrument',
            old_name='pre_bridge_pu_height',
            new_name='pre_bridge_pickup_height',
        ),
        migrations.RenameField(
            model_name='instrument',
            old_name='pre_middle_pu_height',
            new_name='pre_middle_pickup_height',
        ),
        migrations.RenameField(
            model_name='instrument',
            old_name='pre_neck_pu_height',
            new_name='pre_neck_pickup_height',
        ),
        migrations.AlterField(
            model_name='setup',
            name='datetime_in',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 19, 15, 41, 20, 284445, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='setup',
            name='datetime_out',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 19, 15, 41, 20, 284461, tzinfo=utc)),
        ),
    ]
