# Generated by Django 3.2.19 on 2023-05-19 15:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0005_auto_20230519_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='name',
            field=models.CharField(help_text='The name of the instrument', max_length=80),
        ),
        migrations.AlterField(
            model_name='setup',
            name='datetime_in',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 19, 15, 48, 3, 371653, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='setup',
            name='datetime_out',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 19, 15, 48, 3, 371670, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='setup',
            name='name',
            field=models.CharField(help_text='The name of the instrument', max_length=80),
        ),
    ]
