# Generated by Django 3.2.19 on 2023-05-19 17:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('setups', '0006_auto_20230519_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('details', models.CharField(max_length=80)),
            ],
        ),
        migrations.AlterField(
            model_name='setup',
            name='datetime_in',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 19, 17, 44, 38, 448082, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='setup',
            name='datetime_out',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 19, 17, 44, 38, 448097, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_in', models.DateField(auto_now_add=True)),
                ('date_out', models.DateField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'Incomplete'), (1, 'Complete'), (2, 'Partially Complete'), (3, 'Awaiting Parts')], default=0)),
                ('payment_method', models.IntegerField(choices=[(0, 'Cash'), (1, 'Bank Transfer'), (2, 'PayPal'), (3, 'Other')], default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setups.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
