# Generated by Django 3.2.19 on 2023-05-19 19:04

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0008_auto_20230519_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='related_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='setups.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='related_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='setups.order'),
        ),
        migrations.AlterField(
            model_name='setup',
            name='datetime_in',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 19, 19, 4, 36, 361015, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='setup',
            name='datetime_out',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 19, 19, 4, 36, 361052, tzinfo=utc)),
        ),
    ]
