# Generated by Django 3.2.19 on 2023-05-20 17:46

import cloudinary.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('setups', '0009_auto_20230519_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setup',
            name='datetime_in',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 20, 17, 46, 59, 3445, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='setup',
            name='datetime_out',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 20, 17, 46, 59, 3473, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument', models.CharField(blank=True, max_length=80, null=True)),
                ('date_in', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('job_status', models.IntegerField(blank=True, choices=[(0, 'Todo'), (1, 'In progress'), (2, 'Completed')], default=0, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('pre_strings', models.CharField(blank=True, max_length=80, null=True)),
                ('post_strings', models.CharField(blank=True, max_length=80, null=True)),
                ('payment_method', models.IntegerField(blank=True, choices=[(0, 'Cash'), (1, 'Bank Transfer'), (2, 'PayPal'), (3, 'Other')], default=0, null=True)),
                ('payment_status', models.IntegerField(blank=True, choices=[(0, 'Unpaid'), (1, 'Paid')], default=0, null=True)),
                ('date_out', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_in'],
            },
        ),
    ]
