# Generated by Django 3.2.19 on 2023-05-21 19:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0010_auto_20230520_1846'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-date_in'], 'permissions': (('can_create_job', 'Create a job'), ('can_update_job', 'Update a job'), ('can_delete_job', 'Delete a job'))},
        ),
        migrations.AlterField(
            model_name='setup',
            name='datetime_in',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 21, 19, 34, 23, 63545, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='setup',
            name='datetime_out',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 21, 19, 34, 23, 63565, tzinfo=utc)),
        ),
    ]
