# Generated by Django 3.2.19 on 2023-05-25 14:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0013_auto_20230525_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='post_notes',
            field=models.TextField(blank=True, help_text='Provide any additional notes after job completion', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='pre_notes',
            field=models.TextField(blank=True, help_text='Provide any additional notes before job completion if required', null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='post_string_gauges',
            field=models.CharField(blank=True, help_text='Provide either the gauge of the set, e.g. 10-52 or each individual string, from first string to last string', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='pre_string_gauges',
            field=models.CharField(blank=True, help_text='Provide either the gauge of the set, e.g. 10-52 or each individual string, from first string to last string', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='setup',
            name='datetime_in',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 25, 14, 7, 35, 521900, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='setup',
            name='datetime_out',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 25, 14, 7, 35, 521924, tzinfo=utc)),
        ),
    ]
