# Generated by Django 3.2.19 on 2023-05-25 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0014_auto_20230525_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='related_product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='product',
            name='related_order',
        ),
        migrations.RemoveField(
            model_name='setup',
            name='customer',
        ),
        migrations.AlterField(
            model_name='job',
            name='date_in',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='date_out',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Instrument',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Setup',
        ),
    ]
