# Generated by Django 3.2.19 on 2023-05-27 11:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0017_job_public_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='date_in',
            field=models.DateField(blank=True, default=datetime.datetime.now, help_text='Select the date that the instrument was taken in for service', null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='date_out',
            field=models.DateField(blank=True, default=datetime.datetime.now, help_text='Select the date the instrument was returned to the customer', null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='public_status',
            field=models.IntegerField(choices=[(0, 'Hidden'), (1, 'Visible')], default=1, help_text='Select whether this job is visible to the public on the site'),
        ),
    ]
