# Generated by Django 3.2.19 on 2023-05-18 11:20

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('price', models.DecimalField(decimal_places=0, max_digits=4)),
                ('description', models.TextField()),
                ('featured_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('featured_image_alt', models.TextField(help_text='Provide a text description of the featured image for assistive technologies')),
            ],
            options={
                'ordering': ['-price'],
            },
        ),
    ]
