# Generated by Django 3.2.19 on 2023-05-25 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(help_text='Please specify style="width:100%;" in the "Code View" option of the Summernote editor for any embedded images'),
        ),
    ]
