# Generated by Django 3.2.19 on 2023-05-28 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='featured_image_alt',
            field=models.CharField(blank=True, help_text='Provide a text description of the featured image for assistive technologies', max_length=80, null=True),
        ),
    ]
